name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.24
  - pip=25.2
  - wheel=0.45.1
  - setuptools=80.9.0
  - ca-certificates=2025.9.9
  - openssl=3.0.18
  - sqlite=3.50.2
  - readline=8.3
  - tk=8.6.15
  - ncurses=6.5
  - xz=5.6.4
  - zlib=1.3.1
  - libzlib=1.3.1
  - zstd=1.5.7
  - bzip2=1.0.8
  - lz4-c=1.9.4
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ld_impl_linux-64=2.44
  - libgcc-ng=11.2.0
  - libstdcxx-ng=11.2.0
  - libgomp=11.2.0
  - libffi=3.4.4
  - gmp=6.3.0
  - mpfr=4.2.1
  - mpc=1.3.1
  - gmpy2=2.2.1
  - blas=1.0
  - libopenblas=0.3.30
  - nomkl=3.0
  - fsspec=2025.7.0
  - filelock=3.17.0
  - importlib-metadata=8.5.0
  - jinja2=3.1.6
  - markupsafe=3.0.2
  - mpmath=1.3.0
  - networkx=3.2.1
  - six=1.17.0
  - sympy=1.14.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - opentelemetry-api=1.37.0
  - jpeg=9f
  - libpng=1.6.39
  - libtiff=4.7.0
  - openjpeg=2.5.2
  - lerc=4.0.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lcms2=2.16
  - libdeflate=1.22
  - aom=3.6.0
  - dav1d=1.2.1
  - cairo=1.18.4
  - pixman=0.46.4
  - fontconfig=2.15.0
  - freetype=2.13.3
  - graphite2=1.3.14
  - fribidi=1.0.10
  - harfbuzz=10.2.0
  - icu=73.1
  - libxcb=1.17.0
  - xorg-libx11=1.8.12
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - pillow=11.3.0
  - libuv=1.48.0
  - pip
